---
- name: updated system ubuntu
  apt:
    name: openjdk-8-jre
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: install java centos
  yum:
    name: java-1.8.0-openjdk
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'
