---
- name: Creates /data directory
  file:
    path: /data
    state: directory
    mode: 0777

- name: Download kibana tar ball
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/{{ kibana }}-linux-x86_64.tar.gz
    dest: /data/{{ kibana }}-linux-x86_64.tar.gz
    mode: 0755

- name: unzip kibana
  unarchive:
    src: /data/{{ kibana }}-linux-x86_64.tar.gz
    dest: /data/
    remote_src: yes
    creates: /data/{{kibana }}-linux-x86_64/config/kibana.yml

- name: kibana systemd copy
  template:
    src: elk_config/templates/kibana.service.j2
    dest: /etc/systemd/system/kibana.service
    mode: 0644

- name: Update default kibana config
  template:
    src: elk_config/templates/kibana.yml.j2
    dest: /data/{{ kibana }}-linux-x86_64/config/kibana.yml
    mode: 0660

- name: force systemd reload
  systemd:
    daemon_reload: yes

- name: Start the kibana service
  service:
    name: kibana
    state: started
    enabled: yes
