---
# Filebeat Setup
    - name: Creates /data directory
      file:
        path: /data
        state: directory
        mode: "u=rwx,g=rwx,o=rwx"
    - name: Download filebeat tar ball
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.4.0-linux-x86_64.tar.gz
        dest: /data/filebeat-6.4.0-linux-x86_64.tar.gz
        mode: 0755
    - name: unzip filebeat
      unarchive:
        src: /data/filebeat-6.4.0-linux-x86_64.tar.gz
        dest: /data/
        remote_src: yes
        creates: /data/filebeat-6.4.0-linux-x86_64/metricbeat.yml
    - name: logstash systemd copy
      template:
        src: elk_config/templates/filebeat.service.j2
        dest: /etc/systemd/system/filebeat.service
        mode: 0644
    - name: Update default filebeat config
      template:
        src: elk_config/templates/filebeat.yml.j2
        dest: /data/filebeat-6.4.0-linux-x86_64/filebeat.yml
        mode: 0700
    - name: force systemd reload
      systemd:
        daemon_reload: yes
    - name: Start the filebeat service
      service:
        name: filebeat
        state: started
        enabled: yes

